version: '3.8'

services:
  # Letta server for integration tests
  letta:
    image: lettaai/letta:latest
    ports:
      - "8283:8283"
    environment:
      - LETTA_SERVER_HOST=0.0.0.0
      - LETTA_SERVER_PORT=8283
    volumes:
      - letta_data:/app/data
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8283/v1/health"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 30s

  # Test runner service
  test:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - letta
    environment:
      - LETTA_BASE_URL=http://letta:8283
      - PYTHONPATH=/app
    volumes:
      - ./yaml-letta:/app/yaml-letta
      - ./tests:/app/tests
      - ./pytest.ini:/app/pytest.ini
    command: sh -c "sleep 10 && python -m pytest tests/ -v --tb=short"

  # Development service for interactive testing
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - letta
    environment:
      - LETTA_BASE_URL=http://letta:8283
      - PYTHONPATH=/app
    volumes:
      - ./yaml-letta:/app/yaml-letta
      - ./tests:/app/tests
      - ./examples:/app/examples
    command: /bin/bash
    stdin_open: true
    tty: true

volumes:
  letta_data: