name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build test image
      run: docker-compose build test

    - name: Run tests
      run: docker-compose run --rm test

    - name: Stop containers
      if: always()
      run: docker-compose down -v